.TH "main.cpp" 3 "Mon Mar 13 2017" "RSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'accueil\&.h'\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <QLibraryInfo>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for RSQL from the source code\&.
