.TH "mainwindow.h" 3 "Mon Mar 13 2017" "RSQL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QModelIndex>\fP
.br
\fC#include <QListWidgetItem>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RSQL from the source code\&.
